/* samples.js — demo tokens + matching demo keys, generated by tools/gen-samples.mjs.
   These keys are throwaway material for demonstration only. */
(function (root) {
  'use strict';
  root.JWTSamples = {
    "hs256": {
      "label": "HS256 signed",
      "icon": "fa-signature",
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2F1dGguZ2xhY2llci5leGFtcGxlIiwic3ViIjoidXNyXzg4NDIiLCJhdWQiOiJhcGk6Ly9mcm9zdC1nYXRld2F5IiwibmFtZSI6IkVyaWthIE11c3Rlcm1hbm4iLCJlbWFpbCI6ImVyaWthQGdsYWNpZXIuZXhhbXBsZSIsInNjb3BlIjoicHJvZmlsZSB0b2tlbjpyZWFkIiwicm9sZXMiOlsiYW5hbHlzdCJdLCJqdGkiOiJmM2IxYzJkNC1kZW1vIiwiaWF0IjoxNzgxMjUzMTI4LCJuYmYiOjE3ODEyNTMxMjgsImV4cCI6MTkwNzM5NzEyOH0.Muw_xU5XzkhMMgn0eIcOSkmH0JMn4o-slMyydz36bZk",
      "keyHint": "Secret (UTF-8): glacier-demo-secret",
      "key": "glacier-demo-secret",
      "keyFormat": "secret",
      "secretEncoding": "utf8"
    },
    "rs256": {
      "label": "RS256 signed",
      "icon": "fa-certificate",
      "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdsYWNpZXItMjAyNi1yc2EifQ.eyJpc3MiOiJodHRwczovL2F1dGguZ2xhY2llci5leGFtcGxlIiwic3ViIjoic3ZjX3BpcGVsaW5lIiwiYXVkIjpbImFwaTovL2Zyb3N0LWdhdGV3YXkiLCJhcGk6Ly9pY2VmaWVsZCJdLCJzY29wZSI6InBpcGVsaW5lOnJ1biBhcnRpZmFjdHM6d3JpdGUiLCJjbGllbnRfaWQiOiJmcm9zdC1jaSIsImp0aSI6IjdhMWQ5ZTMwLWRlbW8iLCJpYXQiOjE3ODEyNTMxMjgsImV4cCI6MTkwNzM5NzEyOH0.2e-CTqyMp0jtSjqchkkSB_0xqi9BHHeLZJVzI3uxqhbqIH7JBe5Acwym81c3SDwITqrbpDqlq8MWEQQMGq3PcSYhoc_Wv0KJKGHGiPPRiw9bsMcwoyCuTlkNP-AXpmUrea7ZqkE4bNcWkUTfPku8e_9okEkoIMDJh8u2YX08V-Qc4mDoxhqxmUCltRIN-QnWTqlVnFmbA7n8fouknz3QK42DRS0FeYBDxBmzqrGkA3dTMJ6NAp02wBSfX9dxe5CjUbVILIj15w94l5qZFkInnNeEfqumHl8I4FXOuxSVUWcsGcHceh0ue6B_y2CO9cT--NNRtG7h6Oc2QtOyhCnSjA",
      "keyHint": "RSA public key (SPKI PEM)",
      "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9DLt8HMoxQbxr656FDH1\nmEWczLlqydB2F5P3RHvMVfLl313hm/xsNhM1BOxGGLaiJIxtvdh10JabX0BMn/6I\n8PwMEPsLjrwTiKV0ZjNR+QCCa5/5TImMEDmDVbLP72TlnJCownqDi3JSFcJvLCM0\n5QrxWRuEKU92aLALQT6UpNBlU1WNfOCLDgjM5KJoRhv9I7nxYriJ4N9JEA8Sj08X\nPvccM4QUMAGp+ocXSa9f/7WBO3+tqRdH2Z6rDIoFyuGm9IZ1eeUNAV/aN+tgckjI\nxaLtA20IH2ApJfw07GvJhyLOfcCwea4LyAdxSjC6uRT+S94+7XeqETF42fPFKVod\nGQIDAQAB\n-----END PUBLIC KEY-----",
      "keyFormat": "pem"
    },
    "jwe": {
      "label": "JWE encrypted",
      "icon": "fa-lock",
      "token": "eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIiwiY3R5IjoiSldUIiwia2lkIjoiZ2xhY2llci0yMDI2LWVuYyJ9.dlL6ggPKmIAMcLOR5g4f3rzm5R5IzydBoCmjO1fH5sTzpJEoHl5G-_2FRfdOJW8DuP_cewv7nE6WbRa5aV-tEifmjEgNOL-9JoLU2z4D5okrnQPGFY63mmMBl9ikBfHK6qky-VmYqVpe_UcDj-MIH7bfoj4c3g4TB1_nvG_1g9MK7Quq_gdsNxHSu6Gyj_CrlWtLpDehC8ZNsrMCsJ9DUeifReXhtbPCwTxAx4ZxM9RfG3HjN37Z3fmS4c4HUNeXEjXQNtw1PhXDi4p8cIhWwvKhnvs7o9_dlwXc5AuFbHwRRzVadRnYI7jrC41wnfMYNoJphegeZlNb2yhOizMLGw.UEilvTw8XbK7HfxX.m-mFwz9TaXxOxQNf32H2DimsEkkUjIM2dOxdRp6xAkOh5LIUnebaijkBg8IHiPdTE4wDJA90v3ZYuVAk_c3986oCaVOhtA2wYpFb3dsm3x6bRdmvFQOnXjOy67hF_KPKClm5tK1abJcFvU_vqCLEETXBN8_88D4fbijvIzsULRE3d_riLPVQhI3fZ-c_gz3ze3Wh9xNq6JgMxz2tELf9vL32CwJHk2CnknZvXyEQkLGL6yftCuTV3Jgk9K9OTmgchlwHItdrA84CY2_XdYZIdywAu2DZsKz9oR2obJouSDpC4LpwDDV3_V-mUOKP6fXZkb_Vvr74F9jYWouWSkZPhKCZKewx32Kk6Md4hAygi_o1dO0lXqkkMcRqjpP3Gz7Ks9nTRwrkI1jVIREZ3Iq8twsfYIWHOK2aaSUkCygBMY6CQOnhg_CKvgyG-M_78zMuEw.KCFviwPDMDPX6vzwcVQZfw",
      "keyHint": "RSA private key (PKCS#8 PEM) — contains a nested HS256 JWT (secret: glacier-demo-secret)",
      "key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCG0qIMko4ObPeJ\nnKCFw+mMOhTcBguqDC/CwoTzHIv7K6U04+DEyM1HJM6X3mdLISRlY2EaLM9Y0eJU\n/T0kGJqb4yT7G7f0lT/7SbIOwond4BHAAbz4ETmPUeIbh1feW7jjz/7QpqNDgmp3\nEd58dwh+okXjayhNb4dipTjAPJpCbF0OWJhvy3ie1+1JFrsB0qHl5hXr2mChKK7e\nQd0pzZHki5vtEwSouMyd5EECabZZN6XlNdQLsp4VvfeWF26TWWzJgYmgI+JFtJg1\nZcmJKukmByOZUsLSFJR+DwTddu5pyS9jTvRAf2uBNUMLoVKwjMdEgfuKBQJumPAy\niII2xLZ9AgMBAAECggEANycMTntXbHRMEPnHOuFJdWk/JkC83cvNb+02COO5Kb8R\nfqDnzmhcfUmDz+GVvMiqhGVSkCwbiDiXz2+m5tC/0pxpgOW2a3HwsgHUOrB/SIoE\niNjNLmeRdd0n014a5mX8LQllsoIwkInVtq7TJnRlP7RvRZiM7Jx+tC5lmFJSQnBM\n4E+RQswTTN5T9KrZZyFvnKQu8BjYopdSw6U2XwjCK+Xqyt9PGxAPhlNtViJclGgs\na/bLxpL0ozOY6Gsu4VUuQS617mXyk5PoQIQz9ZvJViC9QHBBBOrU8V/YoE2ubbgN\noivYy6aX+rd24M4MlVLmcW6zTVHJVxtF6C9ez4q46wKBgQC8E1FqMitObsEUgyhe\nZNm9MnPbFKhNtiv0C+agdPPeMjbh3lNVl8bTMn4gaOGTgSws1Ijli7SZ1leBoshG\nm7qMWcPU/SOg16JK0Z2YCXuCkuQHW4vdK3GrUjkmVmJkzsujLlp0W6lZJw1pUj9M\nqTkdxai25EucayAH8loL/5RVlwKBgQC3g8rDrAplFfF5Z27HY36UbEpEYwRKKdVa\nB7EWAKmLjAUmS77xq7E95Tu0e3Sto4OffQipERSBxA4x4tO3GYOBC3RcGn3ipJ1d\nJ9lbjvmtTc6Vw1sWDWvxtfFItGfbzYwIReFvhINh1D9zFyrsRs2PahaPXLe08gaE\nQDA6da5fCwKBgCUu+JCzXIaENR42FBwdekMCn4831VKP6r60P6OHm9NZQCqFxxoM\nCN4mhHMp6Tc9eZtfZbVkWo9zphdWNJxpG4e2E5afeZTKLSb3rF2rukSFgBnISq2u\ncim59tyShZ+ClxYrCu0oViHvK6KgBS3F4yn0szd9iUlikJGho5XtsMj/AoGBAJzN\n0a1MDT2+eCwiAvf/vaKYvQSeDoZIJHLe66M/QZ9pLuVAB5F8AOBARLm8W0Aa3Vaj\ngYjkfT88BFz/0aM7+6+B2BTy1emYepWkfQbMre4083XoDKZVJYzMx7Q14iBgC2zu\nOOgOtCwdLXHrs9Nb1DzcixZIRPgpbQQHzK3G7A1tAoGAIDIRSSUKnBSDkkFiRpkP\nXzrWrg8wEM1MB2NPrN+cAj/hFjP/JPCog6fNNaHU/g9cvXTEPuINkoQ4H6MnVHOb\nN9CWWCOQgN48UOLkn8p438VzCV/pmiRGDSFoEjnc2gZ7/bQLfI5VlC/1CmhFVY+h\ndFBYbqtbRTILkzUZtJduZ1s=\n-----END PRIVATE KEY-----",
      "keyFormat": "pem",
      "nestedKey": "glacier-demo-secret"
    }
  };
}(typeof window !== 'undefined' ? window : globalThis));
