/* samples.js — demo tokens + matching demo keys, generated by tools/gen-samples.mjs.
   These keys are throwaway material for demonstration only. */
(function (root) {
  'use strict';
  root.JWTSamples = {
    "hs256": {
      "label": "HS256 signed",
      "icon": "fa-signature",
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2F1dGguZ2xhY2llci5leGFtcGxlIiwic3ViIjoidXNyXzg4NDIiLCJhdWQiOiJhcGk6Ly9mcm9zdC1nYXRld2F5IiwibmFtZSI6IkVyaWthIE11c3Rlcm1hbm4iLCJlbWFpbCI6ImVyaWthQGdsYWNpZXIuZXhhbXBsZSIsInNjb3BlIjoicHJvZmlsZSB0b2tlbjpyZWFkIiwicm9sZXMiOlsiYW5hbHlzdCJdLCJqdGkiOiJmM2IxYzJkNC1kZW1vIiwiaWF0IjoxNzgxMjcxMDA3LCJuYmYiOjE3ODEyNzEwMDcsImV4cCI6MTkwNzQxNTAwN30.1xV_juf5Um934HBtiCztFNIz34W3qS034eP9OxoiRGc",
      "keyHint": "Secret (UTF-8): glacier-demo-secret",
      "key": "glacier-demo-secret",
      "keyFormat": "secret",
      "secretEncoding": "utf8"
    },
    "rs256": {
      "label": "RS256 signed",
      "icon": "fa-certificate",
      "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdsYWNpZXItMjAyNi1yc2EifQ.eyJpc3MiOiJodHRwczovL2F1dGguZ2xhY2llci5leGFtcGxlIiwic3ViIjoic3ZjX3BpcGVsaW5lIiwiYXVkIjpbImFwaTovL2Zyb3N0LWdhdGV3YXkiLCJhcGk6Ly9pY2VmaWVsZCJdLCJzY29wZSI6InBpcGVsaW5lOnJ1biBhcnRpZmFjdHM6d3JpdGUiLCJjbGllbnRfaWQiOiJmcm9zdC1jaSIsImp0aSI6IjdhMWQ5ZTMwLWRlbW8iLCJpYXQiOjE3ODEyNzEwMDcsImV4cCI6MTkwNzQxNTAwN30.rLdwNrSrj-q0QdOJX4rdIzPqzqCxOjvlQwNaIdXdVv28pijSAwHHt1ZawwA3s-qbHewOdBNokW8-yH6OoCioM24HscYjuJOH-L5wxdRsOaoTdrbcD1aY5ONLLwjrTVBxNVte-W1yymP20OyEV40WYBETlMbLyQHyyuXFH-Z_n58R1rKWUB31V09qCLcZOCtP4hgZ3oJCBm7RoYYpepVX9jiNaD1ux88ddBqLE4stLgYBSjK0EFUaUSN1qhONBwoKd1hLfhLVf--YYzPN2IAaEbPCS_joonudg7SEVveGkPa1nnMS1xICbLqvvCrt-H-FRjuYbFCPlycMxPhsQ541Mw",
      "keyHint": "RSA public key (SPKI PEM)",
      "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0YW7t1NLdfY5OdNKXved\nAfDrRx6qSsKnEwzDWZ49HYfDm4rOE+ElU9E7m14LE2pBU5Sm3njoH42estKgDeB/\n2MDUFOFcTL78WNZu+MGYV5tsib3wSln+bsLP3MQJlv/vwSFD0XmLSEI2HdX16Ago\n2L5NP5lYY2obGeltOnyeKqGcyVOQoORIi2juDQM6PXmveFGIXxNkMBltC6keRU3v\n9uZrpfXwB7+VMb+PLZnlaqB3p19ft3Uq09D+UTlvwJiWtGBd9qQ1oghMWIzPSC2I\nMgWze1CmFrxeuXgfyP1GfLsFcIdx7nfeNsDISYfRw+WhTy9WvGMMMg7PTCr6rMOS\niwIDAQAB\n-----END PUBLIC KEY-----",
      "keyFormat": "pem"
    },
    "jwe": {
      "label": "JWE encrypted",
      "icon": "fa-lock",
      "token": "eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIiwiY3R5IjoiSldUIiwia2lkIjoiZ2xhY2llci0yMDI2LWVuYyJ9.lD3MRQmT2F3jcv2p6cAVkmQHiF3315qM5UpOlIuZHlkgaaLZwdBVnStGQXrjvj6_R9nj-NImrv7lZ4o5R07RwxahULheOgmgCAO6DbCBV_jhVgx0pWiRNTNDsIyJaNApR9i9d0iZMGuDLv0KyjY09F3y13y6s4R_MYyEcisZhXXwVqKQwVa_JTCQeKEeYFxP-5LX_-QdlHTUjLE-q0-oEH97vb2_98B0luAreTSvBC96w3QDwAkgTRqFoNey360RtT7vFcdCrZUrLjyb8__2fy4hrL0kfSPUTzYm84jA4iQAKjHqRICJdKf6wFIN3JX9VGZU494g_g_ubrkNtrqMGA.s6x-liXDdWT2oQ47.tGVS2aidaediCbXM6_S-en0ON8zo28K0lTHHVozu0EnuLU4cnKvXvQUFjg0zCg0dReoygix5sAZsfq45Hvkw0DTnMuKL2gQfM15QgM3aiS2yY3mqByNOxX083EneVZpsxgrNQH9v8shOSpqtQk4yZwASm_V-tBLMcw5OACSUG2eKIe7xVr3TcTfMuTXxhU76pbXGplMMe3SdW4STAYe2xnMjx8ClsIxFOx_9hJwd4Dt3RYSBRgeGbHKShssBxr-aQr1IdLUnq1FvjXmBrneS3wpcN4BYPZ4um0Pw4uZZs23BRWM7VTPfHmt5gL0l5vJBneFfZz2UwxfIhpSi_NatZuCJxlK-uz87EhEAkVRfeI0iQFFMCh7PTrk14H_nQMSUT-LdsX_BiCFIPSaJ7klHIzkLIjcG9lrxVuREHYpXOTyh9rCxZjCa2LnZLB92yN8aIw.fa00pREyn9equo3ZE4xJnQ",
      "keyHint": "RSA private key (PKCS#8 PEM) — contains a nested HS256 JWT (secret: glacier-demo-secret)",
      "key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCi5xZcw1Xa6X7f\ntA+Z21anNF6ifcWXHXCpkZjjr9vGjEFLCAKSUF6CCFzISDxFeCcTW5RyRJfZHMG7\nkFaZMNtcQ+i39zlNYEEIWWVC8tDVgTv+3HzLrH7tArt5lvjKAbzTz1igWAx1e5CM\nQMmAcJSNUE749kXRzD48+jlB/IaQ0gMNbSlQrGLdqUWJMXAuSQ03eYChNYWIOqqD\nJoK3y1PIIO2cK/6ckFkQuuevkTwdGRzc5q4zE7nCS1y68M2w804H7LVeDJX8rZ2m\n8DQGocQMfoPOzi8os97tTmB22O17ctoEQ4pH6GwAJCVbocTS7U8T6AUYd0iQ5bcm\nybaDyrHzAgMBAAECggEACmjyCOOCrQaW0PzUsmRN2UmDcqbO5aU/+dYQCxzF0p5L\n3duZLnhsUarvIu1azKWs+ZO0nMi9W2Z3CuFiZ0+z9OVyDa+CvesUvM/ZpLmXls03\nZEX6w5k2UzcFe/Ol2mLaCj8JztVRloBa8FuDhO2s0Ir9QPOb6pg+se7bkdftUXu/\n+5+/LEgDrhBXw/bFSSM9E6WDm5+89reXG233t4zy4xPllhIqekz6LQqtwESTxYUq\n0Fjxe1QuHkW7rAtBrv2hsV7imWEsMy66sgLaKYPseRZz16G2euaylunDkmGaK7rM\niTZnjwcqlab7u1L7uyRGgWGGhDz1aWeiLuJPLmRFQQKBgQDepJxqlKTyX4qxjFgw\nWAbNkCRc2L2t6DVNk/yui6oSghQHUw7bFw8ELmxm2i/obydxlR0Hlxu799VYTy7S\n2YBp082e8CfyFb6KczPVjahrl2sP/mXddayjStDvBDhn064Pzqgw6eMAZhIX3cML\nyYWpDC+dFZ4EudspMSWrHD7CuQKBgQC7TyiY1YHwu31V3SbtMuUzQHsViDPVRkCq\nv2sqJXzL6HpmCwYfF4KGZU+OGfHUKZuU8AYtUQwydGc6WT2YaXZF0sWZeC0poFYk\nhFQyruH+59Djq+F3UOiUDFcl4sjVCgBvAdX74Kqb9uNEXW3RW48ofwnVcWYANhdL\nTKfUl4D0CwKBgCLki3sMprkxjgv7YcrZ0N8giwJeGYQK02fAHKbCTrot1rO7KaXe\nfET8fZK0+TMlUHo1k2IgJYGU+sOnTUBQRBbR0fTp0GjZTY5nNaVvWQjbpzTPeul1\nSsQgspPzBmAHRc1GZwebcC8c0BMbdzj+sUroFQI6ZBR7iERxZmTlvVRJAoGBAKlF\nnjCQMr+1EE16cGVH623nxdPtpLoGpQYputT5z9AOph51s/CBNIn0IHMQ60SK3Xk5\neLuXVOh73ZYTc+C63hG3qq9Itbe6mF6j39t1w/Ky2EoH2NgVHDo+9LreOhSc10t6\nY0EfBc+wzC3KKSZcEgHM3LwxoLZsK5z3B2zOBdGFAoGAVaVkbkPf0+RtcgMcogrM\nZ+d/2acZ5m4W5yLKwdrZcZjh1qGxCDQ/UzVuAUI4hAKcNH+lstwr5+/bB7RJ+3H5\nBZUT2jvXuOTybssiLAw+aYViBMLR9Qm5ZkPD0DqBRHCt0cv1hF0GVEBmZXpdH2xe\nvHyWlZ/Mgk++atmltuL/XFg=\n-----END PRIVATE KEY-----",
      "keyFormat": "pem",
      "nestedKey": "glacier-demo-secret"
    }
  };
}(typeof window !== 'undefined' ? window : globalThis));
